export const GIT_DATA = {
    GET_GIT_DATA: 'GET_GIT_DATA',
    GET_GIT_DATA_PENDING: 'GET_GIT_DATA_PENDING',
    GET_GIT_DATA_FULFILLED: 'GET_GIT_DATA_FULFILLED',
    GET_GIT_DATA_REJECTED: 'GET_GIT_DATA_REJECTED',

}

